blog/urls.py
from django.urls import path
from . import views

urlpatterns = [
    path('', views.post_list, name='post_list'),
    path('post/<int:pk>/', views.post_detail, name='post_detail'),
    path('post/new', views.post_new, name='post_new'),
    path('post/<int:pk>/edit/', views.post_edit, name='post_edit'),
]

mysite/urls.py
from django.contrib import admin
from django.urls import path, include

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('blog.urls')),
    path('users/', include('users.urls')), # users>urls.py에서 관리할거야
]

users/urls.py
from django.urls import path
from . import views

app_name = "users"
urlpatterns = [
    path('login/', views.login_view, name='login'),
    path('logout/',views.logout_view, name='logout'),
    path('signup/', views.sign_up, name='signup')
]

blog/models.py
from django.conf import settings
from django.db import models
from django.utils import timezone



class Post(models.Model):
    author = models.ForeignKey(settings.AUTH_USER_MODEL, on_delete=models.CASCADE)
    title = models.CharField(max_length=200)
    text = models.TextField()
    created_date = models.DateTimeField(
            default=timezone.now)
    published_date = models.DateTimeField(
            blank=True, null=True)

    def publish(self):
        self.published_date = timezone.now()
        self.save()

    def __str__(self):
        return self.title
    

# class User():
#     # 로그인 아이디, 닉네임, 이름, 비밀번호, 상태

users/models.py
from django.db import models
from django.contrib.auth.models import AbstractUser


class User(AbstractUser):
    login_id = models.CharField(max_length=15)
    nickname = models.CharField(max_length=30)  # 닉네임 필드 추가
    is_active = models.BooleanField(default=True)  # 활성 상태 필드 추가

blog/forms.py
from django import forms

from .models import Post

class PostForm(forms.ModelForm):

    class Meta:
        model = Post
        fields = ('title', 'text',)

blog/views.py
from django.shortcuts import render, get_object_or_404
from django.utils import timezone
from .models import Post
from .forms import PostForm
from django.shortcuts import redirect
from django.core.paginator import Paginator, EmptyPage, PageNotAnInteger


def post_list(request):
    posts = Post.objects.all()
    paginator = Paginator(posts, 20)  # 20개의 객체를 한 페이지에 보여줌

    page = request.GET.get('page')
    try:
        objects = paginator.page(page)
    except PageNotAnInteger:
        # 페이지가 정수가 아닐 경우, 첫 번째 페이지를 반환
        objects = paginator.page(1)
    except EmptyPage:
        # 페이지가 범위를 벗어날 경우, 마지막 페이지를 반환
        objects = paginator.page(paginator.num_pages)

    return render(request, 'blog/post_list.html', {'posts': posts, 'page': objects})


def post_detail(request, pk):
    post = get_object_or_404(Post, pk=pk)
    return render(request, 'blog/post_detail.html', {'post': post})


def post_new(request):
    # 저장버튼
    if request.method == "POST":
        form = PostForm(request.POST)
        if form.is_valid():
            post = form.save(commit=False)
            post.author = request.user
            post.published_date = timezone.now()
            post.save()
            return redirect('post_detail', pk=post.pk)
    # + 버튼
    else:
        form = PostForm()
    return render(request, 'blog/post_edit.html', {'form': form})

def post_edit(request, pk):
    post = get_object_or_404(Post, pk=pk)
    if request.method == "POST":
        form = PostForm(request.POST, instance=post)
        if form.is_valid():
            post = form.save(commit=False)
            post.author = request.user
            post.published_date = timezone.now()
            post.save()
            return redirect('post_detail', pk=post.pk)
    else:
        form = PostForm(instance=post)
    return render(request, 'blog/post_edit.html', {'form': form})

users/views.py
from django.shortcuts import render, redirect
from django.contrib.auth import authenticate, login, logout

# Create your views here.

def login_view(request):
    if request.method == "POST":
        username = request.POST["username"]
        password = request.POST["password"]
        user = authenticate(username=username, password=password)
        if user is not None:
            print("인증 성공")
            login(request, user)
            return redirect('/')
        else:
            print("인증 실패")
    return render(request, "users/login.html")

def logout_view(request):
    logout(request)
    return redirect('/')

def sign_up(request):
    return render(request, "users/signup.html")

blog/templates/blog/base.html
{% load static %}
<html>
  <head>
    <title>roommatch</title>
    <link
      rel="stylesheet"
      href="//maxcdn.bootstrapcdn.com/bootstrap/3.2.0/css/bootstrap.min.css"
    />
    <link
      rel="stylesheet"
      href="//maxcdn.bootstrapcdn.com/bootstrap/3.2.0/css/bootstrap-theme.min.css"
    />
    <link
      href="//fonts.googleapis.com/css?family=Lobster&subset=latin,latin-ext"
      rel="stylesheet"
      type="text/css"
    />
    <link rel="stylesheet" href="{% static 'css/blog.css' %}" />
    <link rel="stylesheet" href="{% static 'css/sidebar.css' %}" />
    <link rel="stylesheet" href="{% static 'css/post_list.css' %}" />
  </head>
  <body>
    <header>
      <div class="top_bar">
        <div class="login_info pc">
          <div>
            <ul
              id="webticker"
              style="
                float: left;
                font-weight: bold;
                direction: ltr;
                font-size: 12px;
                color: rgb(85, 85, 85);
              "
            >
              <li style="opacity: 0.8394">접속주소 https://www.roommatch</li>
              <li style="display: none">
                주소변경 및 긴급공지 https://www.roomtmp [name SNS]
              </li>
            </ul>
          </div>
          <div id="login_info_box1">
            {% if user.is_authenticated %}
            <span class="g_nick">
              <img src="/member/level/1.gif" />{{ user.username }} [id]
              Lv.[1]</span
            ><span class="divide">|</span
            ><span class="point"
              ><i class="fab fa-product-hunt" style="color: #ff6e00"></i
              ><a href="{% url 'users:logout' %}">로그아웃</a></span
            >
            <span class="divide">|</span>
            &nbsp;<a
              class="setting"
              href="/Member/Modify.aspx"
              data-toggle="tooltip"
              data-trigger="hover"
              title=" 설정 "
              ><i class="fas fa-cogs"></i
            ></a>
            &nbsp;&nbsp;<a
              class="mail"
              href="/Member/NoteList.aspx?mode=inbox"
              data-toggle="tooltip"
              data-trigger="hover"
              title="쪽지확인"
              ><i class="far fa-envelope"></i> 0</a
            >
            &nbsp;&nbsp;<a
              class="logout"
              href="/Member/Logout.aspx"
              data-toggle="tooltip"
              data-trigger="hover"
              title="로그아웃"
              ><i class="fas fa-times-circle"></i
            ></a>
            {% else %}
            <!-- 로그인 전 -->
            <span class="g_nick"></span
            ><a href="{% url 'users:login' %}">로그인 </a
            ><span class="divide">|</span
            ><span class="point"
              ><a href="{% url 'users:signup' %}"> 회원가입</a></span
            >
            {% endif %}
          </div>
        </div>
      </div>
      <div class="wrap">
        <!-- 로고 -->
        <div class="head">
          <h1>
            <a href="/" title="룸매치">
              <img src="/image/logo.png" alt="룸매치" />
            </a>
          </h1>

          <a class="gnbView mobile right" href="#void" title="전체메뉴보기"></a>
        </div>

        <!-- 검색박스 -->
        <div class="searchBox pc">
          <div class="search">
            <div class="search_input">
              <input
                type="text"
                id="s_keyword_pc"
                placeholder="방 검색 (지역, 업체 명)"
                onkeypress="if(event.keyCode == 13){doSearchClick(document.getElementById('s_keyword_pc').value); return false;}"
              />
            </div>
            <div class="search_button">
              <input
                type="button"
                title="검색전송"
                onclick="doSearchClick(document.getElementById('s_keyword_pc').value);"
              />
            </div>
          </div>
        </div>

        <!-- 사이드 -->
        <div class="side pc">
          <a href="#"> <img src="/Image/pinterest.png" /></a>
          <a href="#"> <img src="/Image/youtube.png" /></a>
          <a href="#"> <img src="/Image/twitter.png" /></a>
          <a href="#"> <img src="/Image/facebook.png" /></a>
        </div>
      </div>
    </header>
    <nav class="pc">
      <div class="nav_header max-width-1200">
        <div class="header_menu">
          <a href="/" class="menu_box home" title="홈"
            ><i class="fa fa-home"></i
          ></a>
          <a href="/Board/List.aspx?id=notice" class="menu_box" title="공지사항"
            ><i class="fas fa-exclamation-triangle"></i>공지사항</a
          >
          <a href="/Board/Chulsuk.aspx" class="menu_box" title="출석체크"
            ><i class="fas fa-user-check"></i>출석체크</a
          >
          <a href="/Board/List.aspx?id=free" class="menu_box" title="자유게시판"
            ><i class="far fa-keyboard"></i>자유게시판</a
          >
          <a href="/Board/List.aspx?id=qna" class="menu_box" title="질문게시판"
            ><i class="far fa-question-circle"></i>질문게시판</a
          >
          <a
            href="/Board/List.aspx?id=review"
            class="menu_box"
            title="후기게시판"
            ><i class="fas fa-user-edit"></i>후기게시판</a
          >
          <a
            href="/Board/List.aspx?id=contactus"
            class="menu_box"
            title="제휴문의"
            ><i class="fas fa-hands-helping"></i>제휴문의</a
          >
          <a href="/" class="menu_box_last" title=""></a>
        </div>
      </div>
    </nav>
    <!-- sidebar -->
    <main class="max-width-1200" style="display: flex">
      <section style="width: 230px">
        {% for type, locations in room_types.items %}
        <div class="type-box">
          <div class="type-name">{{type}}</div>
          <div class="type-region--container">
            {% for location in locations %}
            <div class="type-region">
              <a href="/">{{location}}</a>
              <a href="/" class="review-btn">후기</a>
            </div>
            {% endfor %}
          </div>
        </div>
        {% endfor %}
      </section>
      <div style="flex-grow: 1">{% block content %} {% endblock %}</div>
    </main>
  </body>
</html>

blog/templates/blog/post_detail.html
{% extends 'blog/base.html' %}

{% block content %}
    <div class="post">
        {% if post.published_date %}
            <div class="date">
                {{ post.published_date }}
            </div>
        {% endif %}
        <a class="btn btn-default" href="{% url 'post_edit' pk=post.pk %}"><span class="glyphicon glyphicon-pencil"></span></a>
        <h1>{{ post.title }}</h1>
        <p>{{ post.text|linebreaksbr }}</p>
    </div>
{% endblock %}

blog/templates/blog/post_edit.html
{% extends 'blog/base.html' %}

{% block content %}
    <h1>New post</h1>
    <form method="POST" class="post-form">{% csrf_token %}
        {{ form.as_p }}
        <button type="submit" class="save btn btn-default">Save</button>
    </form>
{% endblock %}

blog/templates/blog/post_list.html
{% extends 'blog/base.html' %} {% block content %}
<div>
  <div class="main_post-container">
    {% for post in page.object_list %}
    <div class="main_post-box">
      <div class="main-post--top">
        <!-- <img src="{{ post.image.url }}" alt="post image" /> -->
        <div class="main-post--type">투룸</div>
      </div>
      <div class="main-post--bottom">
        <div class="main-post--location">장소</div>
        <div class="main-post--author">{{ post.title }}</div>
        <div class="main-post--phone">010-0000-0000</div>
        <div>
          <a href="">프로필</a>
          <a href="">후기</a>
        </div>
      </div>
      <!-- <div class="main-post--date">{{ post.published_date }}</div> -->
      <!-- <h1><a href="{% url 'post_detail' pk=post.pk %}">{{ post.title }}</a></h1> -->
      <!-- <p>{{ post.text|linebreaksbr }}</p> -->
    </div>
    {% endfor %}
  </div>
  <div class="pagination">
    <span class="step-links">
        {% if page.has_previous %}
        <!-- <a href="?page=1">« 처음</a> -->
        <a href="?page={{ page.previous_page_number }}" class="fixed-width">‹ 이전</a>
        {% else %}
        <div class="fixed-width"></div>
        {% endif %}

        <div class="step-container">
        {% for num in page.paginator.page_range %}
        {% if num > page.number|add:'-3' and num < page.number|add:'3' %}
            {% if num == page.number %}
                <a href="?page={{ num }}" class="current">{{ num }}</a>
            {% else %}
                <a href="?page={{ num }}">{{ num }}</a>
            {% endif %}
        {% elif num == 1 or num == page.paginator.num_pages %}
            <a href="?page={{ num }}">{{ num }}</a>
        {% elif num == page.number|add:'-3' or num == page.number|add:'3' %}
            <span>...</span>
        {% endif %}
        {% endfor %}
        </div>

        {% if page.has_next %}
            <a href="?page={{ page.next_page_number }}" class="fixed-width">다음 ›</a>
            <!-- <a href="?page={{ page.paginator.num_pages }}">마지막 »</a> -->
        {% else %}
        <div class="fixed-width"></div>
        {% endif %}
        
    
     
    </span>
  </div>
</div>
{% endblock %}

users/templates/users/login.html
<!-- users>login.html -->

{% extends 'blog/base.html' %}
{% block content %}

<h1>로그인</h1>
<form method="post" action="{% url 'users:login' %}">
    {% csrf_token %}
    <div>
        <label>사용자 ID</label>
        <input type="text" name="username" id="username">
    </div>
    <div>
        <label>비밀번호</label>
        <input type="password" name="password" id="password">
    </div>
    <button type="submit">로그인</button>
</form>

{% endblock %}

users/templates/users/signup.html
{% extends 'blog/base.html' %}
{% block content %}

회원가입페이지

{% endblock %}